### ISSUE TITLE
Migration is going infinite loop

### ISSUE THREAD

**Issue by deafjava** [flyway/flyway#2105]
Flyway version: **5.1.4**

Client: **Gradle plugin/Spring Boot/Intellij IDE**

Database: **H2 in MySQL MODE**

O.S.: **Mac**

When I start the Java Spring Boot application, I expect the one migration, but it's going repeated in infinite loop:

<img width="1134" alt="captura de tela 2018-08-13 as 20 13 51" src="https://user-images.githubusercontent.com/26586714/44063238-3220ef4e-9f36-11e8-9573-02adfb8f0f75.png">

*Part of SQL content:*

```SQL
SET MODE MYSQL;

CREATE TABLE IF NOT EXISTS users (
    id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(1000) NOT NULL
);
```

Flyway config in `yml` file:
```yaml
flyway:
  enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
```

When I try with real *MySQL*, it run correctly, with just one time as expected.
