### ISSUE TITLE
Unable to resolve location

### ISSUE THREAD

**Issue by heruan** [flyway/flyway#2181]
###### Which version and edition of Flyway are you using?

5.2.0

###### Which client are you using?

Spring Boot 2.1.0.RC1

###### Which database are you using (type & version)?

PostgreSQL 10

###### Which operating system are you using?

Ubuntu Server 18.04

###### What did you do?

Set custom location in `application.yml`:

```yml
spring:
  flyway:
    locations:
    - classpath:db/migration/{vendor}/foobar
```

###### What did you expect to see?

Migration to take place.

###### What did you see instead?

`ClassPathScanner: Unable to resolve location classpath:db/migration/{vendor}/foobar`

This stopped working after upgrading from 5.1 to 5.2 (worked before as is).
