### ISSUE TITLE
Flyway module-scoped migration version sequence

### ISSUE THREAD

**Issue by pturovsk** [flyway/flyway#3003]
**Problem:**
At the moment flyway migrations that are defined in separate modules are first grouped together, sorted by <module, version>  order and applied sequentially.

**Description:**
This approach creates a certain limitations and inconveniences:
- Adding a new migration definition in a multi module set up requires from an engineer to first scan across all flyway modules to find the last migration
- It blocks engineers from defining flyway migration in a library, as library migration history can't possibly follow the same sequence as the one define in the project

**Proposal:**
If am not mistaken the only way today to overcome this limitation is to allow migrations to run `out-of-order`.
I wonder if it would be possible to introduce a configuration **flag** to allow each module to have _own independent version sequence_?

**Sample configuration**:

_Project A_: application.yml

```
flyway:
    table: flyway_schema_history
    version-sequence: module-scoped
    locations: classpath:db/project-migrations, classpath:db/library-migrations
```

```
db/
├── project-migrations/
│   ├── v1.sql
│   ├── v2.sql
```

_Library B_:
```
db/
├── library-migrations/
│   ├── v1.sql
│   ├── v2.sql
```
