### ISSUE TITLE
Error creating Oracle schema that already exists, insufficient privileges. It shouldn't try to create it

### ISSUE THREAD

**Issue by rafaborrego** [flyway/flyway#3225]
###### Which version and edition of Flyway are you using?

Community Edition 7.10.0 that is pulled via Maven dependency "flyway-core" 7.10.0. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Spring Boot Java API

###### Which database are you using? (Type & version)

Oracle 12c

###### Which operating system are you using?

MacOs 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have different users to create schemas, create tables and perform queries. I am using the one with table creation permissions and it fails when I run the application due to lack of privileges to create schemas. The schema already exists and I have used a configuration parameter to avoid its re-creation but it seems to be ignored.

I am using it with Java and Spring Boot and have configured:
- In Maven: imported org.flywaydb.flyway-core 7.10.0
- Added a migration script to create a table called "V1__New_table.sql" under "src/main/resources/db/migration/oracle"
- Added the following to a configuration file:
```
spring:
  datasource:
    initialization-mode: never
    spring.datasource.continue-on-error: true
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db_url:db_port:db_name
    user: my_schema
    password: my_password
jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.default_schema: my_schema
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    createSchemas: false
    init-sqls: select user from dual;
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/oracle
    schemas: my_schema
    user: my_schema
    password: my_password
    url: jdbc:oracle:thin:@db_url:db_port:db_name
```

###### What did you expect to see?

Flyway would create the table defined in the migration script and another table to track the migration history

###### What did you see instead?

It tries to create the schema (that already exists) multiple times until it fails with an insufficient privilege error. Before it runs the "init-sqls" query returning the expected result so it can connect to the database with that user. I have tried writing the username and schema on both uppercase and lowercase and get the same error. I think the error may be related to this line in the log "Default schema: null".

When I run "validate" instead of migrate I get this error, what doesn't make sense to me as the Flyway Init scripts did a successful query on the same schema before:
`Validate failed: Schema "my_schema" doesn't exist yet`

Migrate logs:

```
Found resource: db/migration/oracle/V1__New_table.sql
Scanning for classes at classpath:db/migration/oracle
Database: jdbc:oracle:thin:@db_url:db_port:db_name (Oracle 12.2)
Found statement at line 1: select user from dual
Executing SQL: select user from dual
+---------------+
| USER                 |
+---------------+
| MY_SCHEMA    |
+---------------+
DDL Transactions Supported: false
Schemas: my_schema
Default schema: null
....
Creating schema: "my_schema"
Creating schema "my_schema" ...
Rolling back transaction...
Transaction rolled back
Schema creation failed. Retrying in 1 sec ...
...
Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to create schema "my_schema"
----------------------------------------
SQL State  : 42000
Error Code : 1031
Message    : ORA-01031: insufficient privileges
```
