### ISSUE TITLE
Found more than one migration with version n (after switching from version 7.11.4 to the latest)

### ISSUE THREAD

**Issue by dinaant** [flyway/flyway#3335]
###### Which version and edition of Flyway are you using?
7.12.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

same problem with 7.15.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)

PostgreSql 42.2.23 (production) and H2 1.4.200 (testing) 

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

This is one of many integration tests that fail.
```
@SpringBootTest
@Transactional
class CatalogControllerTest {

	@Autowired
	private WebApplicationContext applicationContext;
	@Autowired
	private aRepository aRepository;
	private MockMvc mockMvc;

	@BeforeEach
	void setup() {
		this.mockMvc = MockMvcBuilders .webAppContextSetup(applicationContext).build();
	}

	@Test
	void get_OK() throws Exception {

		aRepository.save(anyDTO);

		this.mockMvc.perform(
				get("endpoint/...")
			.andExpect(status().isOk());
	}

}
```

**NOTE**
up to version 7.11.4 I didn't have any problems

###### What did you expect to see?

I expected flyway to perform migrations correctly

###### What did you see instead?

I received the following exception:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class
path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init 
method failed; nested exception is org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
Offenders:
-> ...\target\classes\db\migration\V1__table.sql (SQL) 
-> ...\target\test-classes\db\migration\V1__table.sql (SQL) (override)
```
**For reasons of compatibility with H2, I need to override some scripts in the folder test/resources/db/migrations**

**Comment by dinaant** [comment]
@Barry-RG @jonnyrobots  any solution?

**Comment by Barry-RG** [comment]
Can you share your flyway location configuration for both the application and test?

**Comment by Barry-RG** [comment]
Additionally, what version of spring boot are you using?

**Comment by dinaant** [comment]
> Can you share your flyway location configuration for both the application and test?

SpringBoot version: 2.5.6

Production | .../main/resources/application.yaml
```
spring:
flyway:
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    schema: ${DATASOURCE_SCHEMA}
    enabled: true
    url: ${DATASOURCE_URL}
    placeholders:
      uuid: uuid_generate_v4()
```

Test | .../test/resources/application.yaml
```
spring:
flyway:
    user: test
    password: test
    schema: public
    enabled: true
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    placeholders:
      uuid: random_uuid()
```
