### ISSUE TITLE
Flyway yields no logs when running via docker-compose and using `useSSL`

### ISSUE THREAD

**Issue by thomaspaulin** [flyway/flyway#3382]
###### Which version and edition of Flyway are you using?
8.4.2. Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
docker-compose

###### Which database are you using? (Type & version)
MySQL 8.0.28

###### Which operating system are you using?
Ubuntu (via WSL2)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I ran `docker-compose up` with the `useSSL` query parameter (it applies when the query parameter is set, regardless of its value), and the following configuration:

EDIT: I'm able to recreate this by running `docker-compose up flyway`

> docker-compose.yml
```
version: '3.7'
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=passwd
      - MYSQL_DATABASE=mydb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  flyway:
    build:
      context: .
    command: -url=jdbc:mysql://db/mydb?useSSL=false -schemas=mydb -user=myuser -password=passwd -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
```

> Dockerfile
```
FROM flyway/flyway:8.4.2

ENV MYSQL_DRIVER_VERSION 8.0.28

RUN curl -o drivers/mysql-connector-java-${MYSQL_DRIVER_VERSION}.jar \
    https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_DRIVER_VERSION}/mysql-connector-java-${MYSQL_DRIVER_VERSION}.jar
```

> V1__Initial_setup.sql
```
CREATE TABLE MyTable (
    MyColumn VARCHAR(100) NOT NULL
);
```

###### What did you expect to see?
The `db` (MySQL) containers logs AND the flyway logs. Similar to what I see when I omit the `useSSL` query parameter from the DB URL, but keep everything else the same; which yields the logs below.

```
flyway_1  | Flyway is up to date
flyway_1  | Flyway Community Edition 8.4.2 by Redgate
flyway_1  | Database: jdbc:mysql://db/mydb (MySQL 8.0)
flyway_1  | Successfully validated 1 migration (execution time 00:00.013s)
db_1      | mbind: Operation not permitted
flyway_1  | Creating Schema History table `mydb`.`flyway_schema_history` ...
flyway_1  | Current version of schema `mydb`: << Empty Schema >>
flyway_1  | Migrating schema `mydb` to version "1 - Initial setup"
flyway_1  | Successfully applied 1 migration to schema `mydb`, now at version v1 (execution time 00:00.054s)
flyway_1  | Fri Jan 21 18:04:16 UTC 2022 WARN: Caught while disconnecting...
flyway_1  |
flyway_1  | EXCEPTION STACK TRACE:
flyway_1  |
flyway_1  |
flyway_1  |
flyway_1  | ** BEGIN NESTED EXCEPTION **
flyway_1  |
flyway_1  | javax.net.ssl.SSLException
flyway_1  | MESSAGE: closing inbound before receiving peer's close_notify
flyway_1  |
flyway_1  | STACKTRACE:
flyway_1  |
flyway_1  | javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
flyway_1  |     at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(Unknown Source)
flyway_1  |     at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(Unknown Source)
flyway_1  |     at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1319)
flyway_1  |     at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
flyway_1  |     at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1750)
flyway_1  |     at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:720)
flyway_1  |     at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:102)
flyway_1  |     at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:114)
flyway_1  |     at org.flywaydb.core.internal.database.base.Database.close(Database.java:385)
flyway_1  |     at org.flywaydb.core.internal.util.IOUtils.close(IOUtils.java:34)
flyway_1  |     at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:222)
flyway_1  |     at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
flyway_1  |     at org.flywaydb.commandline.Main.executeOperation(Main.java:280)
flyway_1  |     at org.flywaydb.commandline.Main.main(Main.java:188)
flyway_1  |
flyway_1  |
flyway_1  | ** END NESTED EXCEPTION **
flyway_1  |
flyway_1  |
flyway-test_flyway_1 exited with code 0
```

###### What did you see instead?
Only the logs for the `db` (MySQL) container. I  did not see logs for Flyway. I waited 25+ minutes in case it was related to a retry which hadn't yet taken effect. Whereas, if I omit `useSSL` I see the above, as expected.
