### ISSUE TITLE
How to use baseline migration in springboot

### ISSUE THREAD

**Issue by cidxie** [flyway/flyway#3707]
### **How to use baseline migration in springboot**
I placed the SQL script starting with B in the configured directory of the spring project, but after executing the migration command, only the script starting with V was executed, and the baseline script starting with B was not executed
This is the configuration in yml:
```
flyway:
    enabled: true
    flyway.baselineOnMigrate: true
    flyway.baselineVersion: 1.0.0
    flyway.validateOnMigrate: true
    flyway.cleanDisabled: true
locations: classpath:db/migration/eyun_2.0
```
This is the execution code:
```
public static void dbMigrate(){
        Map<String, Map<String, String>> datasource = db.getDatasource();
        log.info("============= Start executing the flyway script ===================");
        datasource.forEach((Key,value)->{
            String keyDatasources = Key;
            log.info("============= start executing {} database ===================" ,keyDatasources);
            Flyway flyway = Flyway.configure()
                    .configuration(fc.getFlyway())
                    .dataSource(value.get("url"),value.get("username"),value.get("password"))
                    .locations(value.get("locations"))
                    .schemas(Key)
                    .load();
            flyway.migrate();
            log.info("============= stop executing {} database ===================", keyDatasources);
            log.info("------------------------------------------------------------------------------");
        });
        log.info("============= flyway script execution ends  ===================");
    }
```
The name of the SQL script is B1.1.0__eyun-2.0-init.sql,Under the /migration/eyun_2.0 directory
