### ISSUE TITLE
ERROR: java.lang.StringIndexOutOfBoundsException: begin 0, end 8, length 0 - when running flyway docker container

### ISSUE THREAD

**Issue by sharafat** [flyway/flyway#3714]
###### Which version and edition of Flyway are you using?
Community version 9.21.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
9.21.0 is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Official Docker container

###### Which database are you using? (Type & version)
MySQL 8.0.33

###### Which operating system are you using?
Mac OS X Ventura 13.4.1

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Here's the `docker-compose.yml` config for flyway:

```
### Flyway ################################################
    flyway:
      image: flyway/flyway:${FLYWAY_VERSION}
      environment:
        - FLYWAY_USER=${MYSQL_USER}
        - FLYWAY_PASSWORD=${MYSQL_PASSWORD}
        - FLYWAY_URL=jdbc:mysql://mysql:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false
        - FLYWAY_GROUP=true
        - FLYWAY_LICENSE_KEY=${FLYWAY_LICENSE_KEY}
        - FLYWAY_EDITION=${FLYWAY_EDITION}
      command: -table=schema_version -connectRetries=60 migrate
      volumes:
        - ${APP_CODE_PATH_HOST}/eximus-web/database/migrations/sql:/flyway/sql
        - ${APP_CODE_PATH_HOST}/eximus-web/database/migrations:/flyway/conf
        - ${APP_CODE_PATH_HOST}/eximus-meet/database/migrations/sql:/flyway/meet/sql
        - ${APP_CODE_PATH_HOST}/eximus-meet/database/migrations:/flyway/meet/conf
      depends_on:
        - mysql
```

I'm running the container using `docker-compose up -d flyway`

###### What did you expect to see?

Container migrating migration files

###### What did you see instead?

`ERROR: java.lang.StringIndexOutOfBoundsException: begin 0, end 8, length 0`
