### ISSUE TITLE
Flyway does not resolve classloader correctly on Websphere Liberty

### ISSUE THREAD

**Issue by faltfe** [flyway/flyway#3809]
###### Which version and edition of Flyway are you using?

- [Flyway 9.22.3](https://github.com/flyway/flyway/releases/tag/flyway-9.22.3)
- Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

At the moment I could no test version 10.x.x but I couldn't find any related changes in the changelogs.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven dependency together with Spring Boot 3.1.4

###### Which database are you using? (Type & version)

Oracle inside a Docker container (gvenzl/oracle-xe:18.4.0-slim)

###### Which operating system are you using?

Windows 10 and Windows 11 with Docker for Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We setup a basic Spring Boot application with Flyway and Oracle database (and H2 for testing). The application is compiled into a WAR and deployed onto a Websphere Libery 23.0.0.9. As recommended by IBM the [<feature>springBoot-3.0</feature>](https://www.ibm.com/docs/de/was-liberty/zos?topic=liberty-deploying-spring-boot-application) is enabled and the application located inside the _apps_ folder. Inside the _server.xml_ the application is configured like

```xml
<springBootApplication location="hello.war" id="hello" />
```

A `flyway.location`file is placed in _resources/db/migration_.

###### What did you expect to see?

When starting the application no migration files are found. The reason is that Websphere Liberty changes the file ending from `.war` to `.spring`. Therefore, the `JarFileClassPathLocationScanner` does not add _WEB-INF/classes/_ as a prefix which results in a wrong path.

###### What did you see instead?

When starting a springBootApplication on Webshpere Liberty I would expect that the migration files are found or that there is somekind of documentation that the configuration needs to be changed.

As a workaround we changed the `application.yaml`

```yaml
spring:
  flyway:
    create-schemas: false
    user: ${ORACLE_USER_SCHEMA_OWNER}
    password: ${ORACLE_PASSWORD_SCHEMA_OWNER}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    fail-on-missing-locations: true
    locations: classpath:WEB-INF/classes/db/migration
```
