### ISSUE TITLE
Unable to configure url in toml file

### ISSUE THREAD

**Issue by issy** [flyway/flyway#3848]
###### Which version and edition of Flyway are you using?

`Flyway OSS Edition 10.8.1 by Redgate`

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Sqlite 3.41.2

###### Which operating system are you using?

macOS Sonoma 14.2.1

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I ran the `flyway migrate` command accompanied with the below `flyway.toml` file.

```toml
[flyway]
url="jdbc:sqlite:app.db"
locations=["migrations"]
baselineOnMigrate=true
```

###### What did you expect to see?

I expected the migrations to run successfully.

###### What did you see instead?

```
ERROR: Failed to configure Parameters: url
```

I commented out the url in the toml file and provided the command argument `-url=jdbc:sqlite:app.db`. This ran successfully, despite being the exact same format.

**Comment by Barry-RG** [comment]
In the TOML configuration for Flyway, URL does not exist under the Flyway namespace. Please see [documentation ](https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters/environments/url)and example [TOML configuration file](https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/toml-configuration-file).

Your configuration should look as the following:
```TOML
[flyway]
environment = "app"
locations = ["migrations"]
baselineOnMigrate = true

[environments.app]
url = "jdbc:sqlite:app.db"
```
