### ISSUE TITLE
.sh migration is ignored

### ISSUE THREAD

**Issue by ItchyNitchy** [flyway/flyway#3922]
###### Which version and edition of Flyway are you using?
Docker Flyway OSS Edition 10.15.0 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)

Postgres 16.2-alpine3.19 image

###### Which operating system are you using?

win 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

My current docker-compose setup
```
flyway:
    profiles: [dev, staging, data]
    container_name: ${container_prefix}_flyway
    build:
      args:
        - flyway_image=${flyway_image}
    volumes:
      - ./migrations/csv:/flyway/csv
      - ./migrations:/flyway/sql
    command: -locations=filesystem:${flyway_path} -url=jdbc:postgresql://${db_host}/${db_name} -schemas=${db_schema} -user=${db_user} -password=${db_password} -connectRetries=5 baseline migrate
    environment:
      FLYWAY_PLACEHOLDERS_DBHOST: ${db_host}
      FLYWAY_PLACEHOLDERS_USER: ${db_user}
      FLYWAY_PLACEHOLDERS_PASSWORD: ${db_password}
      FLYWAY_PLACEHOLDERS_DBNAME: ${db_name}
    networks:
      - cmis_network
    depends_on:
      migrator:
        condition: service_completed_successfully

```
Dockerfile
```
ARG flyway_image
FROM ${flyway_image}

RUN apk add postgresql-client
```

I have this set of migrations
![image](https://github.com/flyway/flyway/assets/52591638/e271b2fc-5bed-42b7-92df-80f32c508e13)
![image](https://github.com/flyway/flyway/assets/52591638/b728b57f-d88f-4624-83f7-58adff4d9cff)

.sh Migration content
```
#!/bin/bash

cat /flyway/csv/foo.csv
# | psql -h ${dbhost} -d ${dbname} -U ${user} -c  "copy public."Dictionaries" from STDIN with delimiter as ',';"
```

All .sql migrations are correctly applied but .sh migration is ignored

###### What did you expect to see?

All migrations is applied

###### What did you see instead?

Only .sql migration is validated and applied
