### ISSUE TITLE
Environment overrides override the whole map of placeholders, not the specific ones

### ISSUE THREAD

**Issue by catostrophe** [flyway/flyway#3933]
###### Which version and edition of Flyway are you using?
10.17.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using? (Type & version)
Oracle 21

###### Which operating system are you using?
Ubuntu Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```toml
[flyway.placeholders]
my_placeholder_1 = "value1"
my_placeholder_2 = "value2"

[environments.prod.flyway.placeholders]
my_placeholder_2 = "new value2"
```

###### What did you expect to see?
I expect that on the `prod` env only the overridden placeholders change.
```toml
placeholders = { my_placeholder_1 = "value1", my_placeholder_2 = "new value2" }
```

I expect that there should be an option to override only specific placeholders, not the whole set (e.g., I have 20 of them, but want to override only 1).

###### What did you see instead?
I see that on the `prod` env the whole placeholders map is replaced.
```toml
placeholders = { my_placeholder_2 = "new value2" }
```
