### ISSUE TITLE
Running flyway in docker-compose fails to connect to database.

### ISSUE THREAD

**Issue by sorenwacker** [flyway/flyway#3937]
For example, when trying to run OpenMetadata with flyway, the migration stops because of connection issues. Here is a minimal setup that produces the error on a Ubuntu 22.04 system with Docker Compose version v2.29.1:

```
version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flyway

  flyway:
    image: flyway/flyway:7-alpine
    command: -url=jdbc:postgresql://db:5432/testdb -user=testuser -password=testpass -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flyway

networks:
  flyway:
    driver: bridge
```
Results in:

```
docker compose up
WARN[0000] /home/sdrwacker/openmetadata/flyway-test/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/0
 ✔ Container flyway-test-db-1      Created                                                                                                                   0.0s 
 ✔ Container flyway-test-flyway-1  Recreated                                                                                                                 0.1s 
Attaching to db-1, flyway-1
db-1      | 
db-1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1      | 
db-1      | 2024-08-06 11:08:13.243 UTC [1] LOG:  starting PostgreSQL 13.15 (Debian 13.15-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1      | 2024-08-06 11:08:13.243 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1      | 2024-08-06 11:08:13.243 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1      | 2024-08-06 11:08:13.251 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1      | 2024-08-06 11:08:13.259 UTC [27] LOG:  database system was shut down at 2024-08-06 11:08:08 UTC
db-1      | 2024-08-06 11:08:13.264 UTC [1] LOG:  database system is ready to accept connections
flyway-1  | WARNING: Connection error: The connection attempt failed. (Caused by connect timed out) Retrying in 1 sec...
```

Is there any additional configuration needed to make this work again?
