### ISSUE TITLE
RSA public key is not available client side (option serverRsaPublicKeyFile not set) [re-raise]

### ISSUE THREAD

**Issue by lexrj** [flyway/flyway#4034]
Re-raised from https://github.com/flyway/flyway-docker/issues/117

I am still observing this from a version pulled today.

My compose file:
```
services:
  flyway:
    image: flyway/flyway
    platform: linux/amd64
    command: -url=jdbc:mysql://db/application-metadata?allowPublicKeyRetrieval=true -user=app -password=test -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
      - ./sql:/flyway/sql/base
      - ./container/sql:/flyway/sql/compose
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: application-metadata
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s # How long can a command hang before it's a failure
      interval: 1s # Interval after start period
      start_period: 1s # How long until failures actually count
      start_interval: 1s # Interval during start period
      retries: 10 # How many failures after start period
```

And the output is:

```
flyway-1  | WARNING: Connection error: Could not connect to address=(host=db)(port=3306)(type=master) : Socket fail to connect to host:db, port:3306. Connection refused
flyway-1  | (Caused by Connection refused)
flyway-1  | Retrying in 1 sec...
flyway-1  | WARNING: Connection error: Could not connect to address=(host=db)(port=3306)(type=master) : Socket fail to connect to host:db, port:3306. Connection refused
flyway-1  | (Caused by Connection refused)
flyway-1  | Retrying in 2 sec...
flyway-1  | WARNING: Connection error: Could not connect to address=(host=db)(port=3306)(type=master) : RSA public key is not available client side (option serverRsaPublicKeyFile not set)
flyway-1  | (Caused by RSA public key is not available client side (option serverRsaPublicKeyFile not set))
flyway-1  | Retrying in 4 sec...
```
